"""
Огромная база триггер-слов для всех реакций Mi-Mi-Mi.
Каждая реакция имеет список ключевых слов на русском и английском.
opencode сам решает когда вызывать каждую реакцию по этим словам.
"""

TRIGGERS = {
    "mimimi": {
        "label": "Недовольство",
        "emoji": "😤",
        "color": "#DC2626",
        "bg_color": "#1a0a0a",
        "desc": "Пользователь недоволен результатом кода",
        "keywords_ru": [
            "плохо", "неправильно", "ужасно", "ерунда", "бред", "фигня", "отстой",
            "говно", "хрень", "лажа", "косяк", "баг", "не работает", "сломалось",
            "ошибка", "дебил", "идиот", "тупой", "урод", "мудак",
            "нахуй", "пиздец", "хуйня", "херня", "дерьмо", "какашка",
            "убого", "отвратительно", "бездарно", "криво", "тупо", "глупо",
            "бестолково", "бесполезно", "никуда не годится", "не катит",
            "не айс", "мимо", "не то", "всё не так", "полный отстой",
            "дрянь", "муть", "чепуха", "ахинея", "дичь", "кал",
            "ни о чём", "пустая трата времени", "некуда", "беда",
            "катастрофа", "провал", "фейл", "позор", "срам",
            "неудачно", "бездарно", "халтура", "тяп-ляп", "на отвали",
            "лишь бы", "кое-как", "липа", "фуфло", "развод",
            "не фонтан", "так себе", "сойдёт", "норм но не то",
            "отвратительно", "мерзко", "гадко", "противно",
            "разочарование", "облом", "неудача", "провалище",
            "жесть", "пипец", "капец", "полный абзац",
            "зачем так", "почему так", "что за", "это что",
            "переделай", "исправь", "перепиши", "удали",
            "не подходит", "не то совсем", "совсем не то",
            "мимо кассы", "в молоко", "пальцем в небо",
            "выбрось", "убери", "зачем это", "нафиг надо",
        ],
        "keywords_en": [
            "bad", "wrong", "terrible", "awful", "garbage", "trash", "suck",
            "shit", "fuck", "crap", "horrible", "dreadful", "poor",
            "lousy", "pathetic", "abysmal", "atrocious", "disgusting",
            "appalling", "vile", "gross", "disappointing", "useless",
            "worthless", "broken", "buggy", "crashing", "failing",
            "disastrous", "miserable", "crummy", "lame", "wack",
            "terrible code", "bad code", "wrong approach",
            "this sucks", "that sucks", "it sucks",
            "not working", "doesn't work", "broken",
            "fix this", "rewrite", "redo", "remove",
            "hate it", "don't like", "not good",
            "worst", "hideous", "fugly", "messy",
            "spaghetti", "garbage code", "trash code",
            "what is this", "what the hell", "what the fuck",
            "are you kidding", "you serious", "you kidding me",
            "nope", "no way", "absolutely not",
            "rubbish", "rubbish code", "nonsense",
            "unacceptable", "intolerable", "inexcusable",
            "amateur", "amateurish", "childish",
            "embarrassing", "shameful", "disgraceful",
            "frustrating", "infuriating", "annoying",
        ],
    },

    "bravo": {
        "label": "Восхищение",
        "emoji": "🌟",
        "color": "#22C55E",
        "bg_color": "#0a1a0a",
        "desc": "Пользователь доволен результатом, код отличный",
        "keywords_ru": [
            "отлично", "прекрасно", "замечательно", "великолепно",
            "браво", "супер", "класс", "круто", "топ", "огонь",
            "шикарно", "бомбически", "потрясающе", "гениально",
            "идеально", "безупречно", "превосходно",
            "молодец", "умница", "суперски",
            "ахуенно", "охренительно", "заебись", "кайф",
            "шик", "блеск", "великолепно", "роскошно",
            "офигенно", "офигительно", "обалденно", "потрясно",
            "клёво", "крутяк", "бомба", "ракета", "космос",
            "гуд", "найс", "бест", "перфект",
            "красиво", "элегантно", "изящно", "стильно",
            "мощно", "сильно", "профессионально",
            "вот это да", "вот это дело", "так держать",
            "продолжай", "суперски", "здорово",
            "восхитительно", "бесподобно", "непревзойдённо",
            "эталонно", "образцово", "показательно",
            "да", "да да да", "yes", "в точку",
        ],
        "keywords_en": [
            "good", "great", "perfect", "excellent", "amazing",
            "awesome", "fantastic", "wonderful", "brilliant",
            "superb", "outstanding", "incredible", "magnificent",
            "splendid", "marvelous", "terrific",
            "bravo", "congratulations", "well done",
            "nice", "cool", "neat", "impressive",
            "beautiful code", "clean code", "elegant",
            "genius", "masterpiece", "flawless",
            "impeccable", "exemplary", "remarkable",
            "notable", "exceptional", "extraordinary",
            "phenomenal", "spectacular", "sensational",
            "perfect solution", "great work", "nice job",
            "kudos", "props", "respect", "cheers",
            "love it", "like it", "amazing work",
            "brilliant solution", "genius move",
            "well played", "nicely done", "job well done",
            "gold star", "top notch", "first rate",
            "a grade", "a plus", "perfect code",
        ],
    },

    "facepalm": {
        "label": "Тупая ошибка",
        "emoji": "🤦",
        "color": "#F59E0B",
        "bg_color": "#1a1400",
        "desc": "Пользователь сделал глупую ошибку",
        "keywords_ru": [
            "фейспалм", "боже", "господи", "дурак", "дура",
            "глупость", "тупость", "идиотизм", "кретин",
            "дебилизм", "абсурд", "нонсенс", "дичь",
            "ересь", "чушь", "ахинея", "околесица",
            "рукалицо", "пц", "ппц",
            "ну как так", "как так", "да ладно", "серьёзно",
            "реально", "не может быть", "да ну",
            "элементарно", "очевидно", "пропустил",
            "забыл", "проворонил", "не заметил",
            "опечатка", "мелочь", "пустяк",
            "глупейшая ошибка", "детская ошибка",
            "капитан очевидность", "очевидное",
            "facepalm", "пиздец", "просто пиздец",
            "ну ёбаный в рот", "ёбаный",
            "слепой", "не внимательный",
            "копейка", "мелкая ошибка",
            "скобку забыл", "точку с запятой",
            "отступы", "индентация",
            "элементарно же", "банально",
        ],
        "keywords_en": [
            "facepalm", "dumb", "stupid", "silly", "ridiculous",
            "absurd", "nonsense", "idiot", "moron", "fool",
            "d'oh", "seriously", "unbelievable", "facepalm",
            "are you kidding", "you kidding me",
            "can't believe", "no way", "you serious",
            "basic mistake", "simple error", "typo",
            "missed that", "overlooked", "forgot",
            "obvious", "elementary", "clearly",
            "facepalm moment", "dumb mistake",
            "rookie error", "beginner mistake",
            "how could I miss", "how could you",
            "sigh", "really", "come on",
            "you're joking", "must be joking",
            "palms face", "hit forehead",
            "so obvious", "staring right at",
            "right there", "in front of you",
        ],
    },

    "confused": {
        "label": "Непонимание",
        "emoji": "😵‍💫",
        "color": "#A855F7",
        "bg_color": "#0a001a",
        "desc": "Пользователь запутался в коде или требовании",
        "keywords_ru": [
            "непонятно", "странно", "запутанно", "мутно",
            "неясно", "что за", "как так", "непонятки",
            "загадка", "туманно", "смутно", "неразбериха",
            "путаница", "головоломка",
            "сложно", "замысловато", "мудрёно",
            "заумно", "наворочено", "намудрил",
            "хз", "хер знает", "хуй знает",
            "ничего не понятно", "не врубаюсь",
            "че за нах", "штош",
            "в чем смысл", "зачем это",
            "почему так", "откуда это",
            "что это значит", "как это работает",
            "где логика", "логика где",
            "инопланетный код", "магия",
            "магический код", "нечитаемо",
            "зачем столько", "нагромождение",
            "каша", "винегрет", "солянка",
            "ад", "адский код", "адронный коллайдер",
            "эскалация", "оверкилл",
            "переусложнено", "overcomplicated",
        ],
        "keywords_en": [
            "confused", "confusing", "unclear", "weird", "strange",
            "odd", "puzzling", "baffling", "bewildered",
            "perplexed", "mysterious", "enigmatic", "cryptic",
            "what", "huh", "what does this",
            "how does this", "where is",
            "i don't understand", "don't get it",
            "what is this", "what the",
            "makes no sense", "doesn't make sense",
            "confusing code", "weird code",
            "overcomplicated", "overengineered",
            "too complex", "unnecessary complexity",
            "magic", "magic number", "spaghetti",
            "wtf", "wth", "what in the world",
            "lost", "confused", "uncertain",
            "unclear logic", "tangled", "messy",
            "why is this here", "what does this do",
            "i'm lost", "i don't follow",
            "explain", "clarify", "elaborate",
        ],
    },

    "party": {
        "label": "Праздник",
        "emoji": "🎉",
        "color": "#EC4899",
        "bg_color": "#1a0014",
        "desc": "Код заработал с первой попытки или большой успех",
        "keywords_ru": [
            "ура", "победа", "заработало", "получилось",
            "взлетело", "запустилось", "компилируется",
            "готово", "сделано", "работает", "полетело",
            "поехало", "завелось", "запуск",
            "первый запуск", "с первого раза",
            "без ошибок", "чисто", "на ура",
            "компиляция успешна", "билд ок",
            "деплой", "залили", "выкатили",
            "релиз", "выпустили", "готов к релизу",
            "счастье", "радость", "эйфория",
            "порадовал", "обрадовал", "успех",
            "триумф", "виктория", "вуаля",
            "есть", "оно живое", "ай да пушкин",
            "всё ок", "всё гуд", "всё работает",
            "тесты прошли", "тесты зелёные",
            "билд зелёный", "зелёный свет",
            "it works", "finally works",
        ],
        "keywords_en": [
            "party", "celebrate", "celebration", "victory", "win",
            "success", "done", "finally", "works",
            "compiled", "deployed", "ship", "launch",
            "yes", "woohoo", "woo", "yay", "wow",
            "first try", "first attempt", "perfect run",
            "zero errors", "clean build", "green build",
            "tests pass", "all green", "all passing",
            "it works", "it compiles", "it runs",
            "successful", "complete", "finished",
            "released", "shipped", "live",
            "amazing", "unbelievable", "magical",
            "booyah", "yesss", "let's go",
            "we did it", "we made it",
            "great success", "huge win",
            "milestone", "breakthrough",
            "eureka", "jackpot", "bingo",
            "bullseye", "hit the mark",
        ],
    },

    "angry": {
        "label": "Ярость",
        "emoji": "🤬",
        "color": "#991B1B",
        "bg_color": "#1a0000",
        "desc": "Пользователь в ярости от кода или требований",
        "keywords_ru": [
            "бесит", "злость", "ярость", "гнев", "ненависть",
            "достало", "заебало", "задолбало",
            "пипец", "капец", "жесть", "писец",
            "заколебало", "выбесило", "раздражает",
            "трясёт", "взбешён", "в ярости",
            "кипит", "кипячусь", "взбесило",
            "ненавижу", "презираю", "ненавистно",
            "убейте", "прибейте", "расстрелять",
            "сжечь", "удалить нахуй",
            "всё сжечь", "стереть в порошок",
            "бешенство", "агрессия", "злоба",
            "ору", "кричу", "матерюсь",
            "маты", "мат", "ругательства",
            "уёбок", "пидор", "гандон",
            "хуесос", "залупа", "мудила",
            "долбоёб", "ебанат", "пидорас",
            "разъёб", "разъебай", "разгильдяй",
            "дебил ёбаный", "мудак ёбаный",
            "твою мать", "ёбаный в рот",
            "ёб твою мать", "нахуя",
            "какого хера", "какого хуя",
            "зачем блять", "почему блять",
            "терпеть не могу", "выносит мозг",
            "бесит просто", "бесит нереально",
            "трясёт от злости", "взрыв мозга",
            "сорваться", "срыв", "истерика",
        ],
        "keywords_en": [
            "angry", "mad", "furious", "livid", "enraged",
            "pissed", "frustrated", "infuriated", "irate",
            "fuming", "raging", "annoyed", "irritated",
            "hate", "hatred", "despise", "loathe",
            "goddammit", "goddamn", "damn",
            "son of a bitch", "motherfucker",
            "what the fuck", "how the fuck",
            "who the fuck", "why the fuck",
            "fucking hell", "fucking shit",
            "bullshit", "horseshit",
            "piss off", "fuck off",
            "fuck this", "fuck that",
            "i give up", "i quit",
            "this is bullshit", "this is shit",
            "so done", "so over it",
            "unacceptable", "intolerable",
            "fed up", "sick of it", "tired of",
            "are you kidding me", "you serious",
            "enough", "stop", "no more",
            "rage", "anger", "wrath",
        ],
    },
}

# Собираем все ключевые слова в плоский список для opencode
ALL_KEYWORDS_RU = []
ALL_KEYWORDS_EN = []
for reaction, data in TRIGGERS.items():
    ALL_KEYWORDS_RU.extend(data["keywords_ru"])
    ALL_KEYWORDS_EN.extend(data["keywords_en"])

# Дедупликация
ALL_KEYWORDS_RU = list(dict.fromkeys(ALL_KEYWORDS_RU))
ALL_KEYWORDS_EN = list(dict.fromkeys(ALL_KEYWORDS_EN))

def find_best_reaction(text: str) -> str:
    """Находит подходящую реакцию по тексту. Возвращает ключ реакции или None."""
    text_lower = text.lower()
    best_reaction = None
    best_score = 0

    for reaction, data in TRIGGERS.items():
        for kw in data["keywords_ru"] + data["keywords_en"]:
            if kw in text_lower:
                score = len(kw)
                if score > best_score:
                    best_score = score
                    best_reaction = reaction

    return best_reaction
